[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@solady/=lib/solady/src/',
]

[fuzz]
runs = 256

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
ffi = true

[lint]
lint_on_build = false

[profile.opt]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
