[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "solmate/=lib/solmate/src/",
    "foundry-devops/=lib/foundry-devops/src/",
]

[fuzz]
runs = 256

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
ffi = true

[lint]
lint_on_build = false

[profile.opt]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200


[profile.ci]
fuzz = { runs = 128 }
optimizer = false
ffi = false




# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
