[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "solmate/=lib/solmate/src/",
    "foundry-devops/=lib/foundry-devops/src/",
]

ffi = true
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fuzz]
runs = 256

[profile.ci]
optimizer = false
ffi = false
fs_permissions = []

[lint]
lint_on_build = false

[profile.opt]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
